// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Mirrors the build-script pattern from `tauri-apps/plugins-workspace`
// (e.g. plugins/haptics/build.rs). `tauri_plugin::Builder` is what wires
// up the iOS Swift module path and emits the autogenerated per-command
// permission schemas under `permissions/autogenerated/`.

const COMMANDS: &[&str] = &[
    "start_capture",
    "stop_capture",
    "check_permissions",
    "request_permissions",
];

fn main() {
    let result = tauri_plugin::Builder::new(COMMANDS)
        .ios_path("ios")
        .try_build();

    // The official plugins swallow Err() when building docs against a
    // platform that doesn't have the native toolchain (e.g. docs.rs
    // building an Android-only plugin on Linux). We mirror that here so
    // `cargo doc` on a non-iOS host still succeeds.
    if !(cfg!(docsrs) && std::env::var("TARGET").unwrap_or_default().contains("ios")) {
        result.unwrap();
    }
}
